# Generated by Django 3.2.3 on 2021-06-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitedetail',
            old_name='personName',
            new_name='websiteName',
        ),
    ]
