# Generated by Django 3.2.3 on 2021-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0002_rename_personname_websitedetail_websitename'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbLink', models.CharField(max_length=250)),
                ('twittterLink', models.CharField(max_length=250)),
                ('googleLink', models.CharField(max_length=250)),
                ('gitLink', models.CharField(max_length=250)),
                ('linkedinLink', models.CharField(max_length=250)),
                ('InstaLink', models.CharField(max_length=250)),
            ],
        ),
    ]
