# Generated by Django 3.2.3 on 2021-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='InstaLink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='fbLink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='gitLink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='googleLink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedinLink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='twittterLink',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
