# Generated by Django 3.2.3 on 2021-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0004_auto_20210627_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='InstaLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='fbLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='gitLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='googleLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='linkedinLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='twittterLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
