# Generated by Django 3.2.3 on 2021-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0005_auto_20210627_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
    ]
