# Generated by Django 3.2.3 on 2021-06-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0006_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=5000)),
                ('phone', models.CharField(max_length=12)),
                ('sender', models.EmailField(max_length=254)),
            ],
        ),
    ]
