# Generated by Django 3.2.3 on 2021-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
