# Generated by Django 3.2.3 on 2021-07-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0009_auto_20210704_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
