# Generated by Django 3.2.3 on 2021-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0010_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedetail',
            name='websiteName',
            field=models.CharField(max_length=100),
        ),
    ]
