# Generated by Django 3.2.3 on 2021-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWebsiteBuilder', '0011_alter_websitedetail_websitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='homepageContent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
